---
- name: "join swarm as manager"
  shell: "docker swarm join --token {{ hostvars[swarm_manager_init_host]['manager_token']['stdout'] }} {{ hostvars[swarm_manager_init_host]['ansible_eth0']['ipv4']['address'] }}:2377"
  when: docker_info.stdout.find("Swarm{{':'}} inactive") != -1 and not (swarm_init | default(false)) | bool
  retries: 3
  delay: 20
