---
- name: "initialize docker swarm"
  shell: docker swarm init --advertise-addr "{{ ansible_eth0['ipv4']['address'] }}"
  when: "docker_info.stdout.find('Swarm: inactive') != -1"

  
- name: "register manager token"
  shell: docker swarm join-token -q manager
  register: manager_token

- name: "register worker token"
  shell: docker swarm join-token -q worker
  register: worker_token
